// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=interface_mock.go -package=estimate
//

// Package estimate is a generated GoMock package.
package estimate

import (
	context "context"
	reflect "reflect"

	eth "github.com/WangWilly/swap-estimation/pkgs/clients/eth"
	gomock "go.uber.org/mock/gomock"
)

// MockEthClient is a mock of EthClient interface.
type MockEthClient struct {
	ctrl     *gomock.Controller
	recorder *MockEthClientMockRecorder
	isgomock struct{}
}

// MockEthClientMockRecorder is the mock recorder for MockEthClient.
type MockEthClientMockRecorder struct {
	mock *MockEthClient
}

// NewMockEthClient creates a new mock instance.
func NewMockEthClient(ctrl *gomock.Controller) *MockEthClient {
	mock := &MockEthClient{ctrl: ctrl}
	mock.recorder = &MockEthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEthClient) EXPECT() *MockEthClientMockRecorder {
	return m.recorder
}

// UniV2ReservePair mocks base method.
func (m *MockEthClient) UniV2ReservePair(ctx context.Context, pairAddrStr string) (*eth.ReservePair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UniV2ReservePair", ctx, pairAddrStr)
	ret0, _ := ret[0].(*eth.ReservePair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UniV2ReservePair indicates an expected call of UniV2ReservePair.
func (mr *MockEthClientMockRecorder) UniV2ReservePair(ctx, pairAddrStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UniV2ReservePair", reflect.TypeOf((*MockEthClient)(nil).UniV2ReservePair), ctx, pairAddrStr)
}
